name: Sync Azure App Configuration (no OIDC)

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: "Choose environment (dev/test/prod)"
        required: true
        default: "dev"

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    # Bind this run to the chosen GitHub Environment so it can read that env's secrets/vars
    environment: ${{ inputs.targetEnv }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update App Configuration via connection string
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail

            # ---- Pull env-specific values from GitHub Environment ----
            APPCONFIG_CONNECTION_STRING='${{ secrets.APPCONFIG_CONNECTION_STRING }}'
            VM_LABEL='${{ vars.VM_LABEL }}'

            API_BASEURL='${{ vars.API_BASEURL }}'
            FEATURE_X_ENABLED='${{ vars.FEATURE_X_ENABLED }}'

            DB_CONN_SECRET_URI='${{ secrets.DB_CONN_SECRET_URI }}'
            SENDGRID_KEY_URI='${{ secrets.SENDGRID_KEY_URI }}'

            # Safety check
            if [ -z "$APPCONFIG_CONNECTION_STRING" ]; then
              echo "ERROR: APPCONFIG_CONNECTION_STRING not set for this environment."
              exit 1
            fi

            echo "Writing to App Configuration with label: $VM_LABEL"

            # Ensure App Configuration extension exists (safe if already present)
            az extension add --name appconfig --only-show-errors || true

            # --- Upsert plain key-values (examples) ---
            az appconfig kv set \
              --connection-string "$APPCONFIG_CONNECTION_STRING" \
              --key "App:Api:BaseUrl" \
              --label "$VM_LABEL" \
              --value "$API_BASEURL" \
              --yes

            az appconfig kv set \
              --connection-string "$APPCONFIG_CONNECTION_STRING" \
              --key "Features:FeatureX:Enabled" \
              --label "$VM_LABEL" \
              --value "$FEATURE_X_ENABLED" \
              --content-type "text/plain" \
              --yes

            # --- Upsert Key Vault references (examples) ---
            if [ -n "$DB_CONN_SECRET_URI" ]; then
              az appconfig kv set-keyvault \
                --connection-string "$APPCONFIG_CONNECTION_STRING" \
                --key "ConnStrings:Db" \
                --label "$VM_LABEL" \
                --secret-identifier "$DB_CONN_SECRET_URI" \
                --yes
            fi

            # Optional summary
            az appconfig kv list \
              --connection-string "$APPCONFIG_CONNECTION_STRING" \
              --label "$VM_LABEL" \
              --top 20 \
              --query "[].{key:key, label:label, contentType:content_type, lastModified:last_modified}" \
              -o table
