      - name: Build JSON and push keys (Feature:AutoUpdate, Feature:DataExplorer)
        uses: azure/cli@v2
        with:
          # Pin to a stable CLI if you want; otherwise omit to use the action's default.
          # azcliversion: 2.62.0
          inlineScript: |
            set -euo pipefail

            # Make the CLI auto-install any missing extension (no prompts)
            az config set extension.use_dynamic_install=yes_without_prompt
            az --version

            # ---- Inputs from GitHub Environment ----
            CS='${{ secrets.APPCONFIG_CONNECTION_STRING }}'
            LABEL_RAW='${{ vars.TARGET_LABEL }}'

            if [ "$LABEL_RAW" = "_NO_LABEL_" ] || [ -z "${LABEL_RAW:-}" ]; then
              LABEL=""
            else
              LABEL="$LABEL_RAW"
            fi

            # ---------- Feature:AutoUpdate ----------
            AUTO_SCRIPT='VEStudio.schedule'
            AUTO_REPORT='laststatuses.txt'
            AUTO_SAVE='false'      # keep as string unless your app expects JSON booleans
            AUTO_EMAIL='false'

            # ---------- Feature:DataExplorer ----------
            DEX_READ_ROLE='DDT_DataExplorer'
            DEX_MODIFY_ROLE='DDT_DataExplorer_Modify'
            STORAGE_ACCOUNT='${{ vars.STORAGE_ACCOUNT }}'
            SHARE_USERCONTENT='usercontent'

            if [ -z "$CS" ]; then
              echo "ERROR: APPCONFIG_CONNECTION_STRING is not set for this environment."
              exit 1
            fi

            # We only need jq; no need to apt-get the appconfig extension anymore
            sudo apt-get update -y >/dev/null 2>&1 || true
            sudo apt-get install -y jq >/dev/null 2>&1

            # Prepare label flag
            labelFlag=()
            if [ -n "$LABEL" ]; then
              labelFlag+=(--label "$LABEL")
              echo "Using label: $LABEL"
            else
              echo "Using NO label"
            fi

            # ---------- Build JSON values with jq ----------
            AUTO_JSON=$(jq -c -n \
              --arg script "$AUTO_SCRIPT" \
              --arg report "$AUTO_REPORT" \
              --arg save "$AUTO_SAVE" \
              --arg email "$AUTO_EMAIL" \
              '{ ScriptFileName:$script,
                 ReportFileName:$report,
                 SaveFullReport:$save,
                 SendReportByEmail:$email }')

            # UNC base: \\<acct>.file.core.windows.net\<share>
            UNC_BASE="\\\\\\${STORAGE_ACCOUNT}.file.core.windows.net\\${SHARE_USERCONTENT}"

            DEX_JSON=$(jq -c -n \
              --arg readRole   "$DEX_READ_ROLE" \
              --arg modifyRole "$DEX_MODIFY_ROLE" \
              --arg queries    "${UNC_BASE}\\Queries" \
              --arg highlights "${UNC_BASE}\\Highlights" \
              '{ ReadRole:$readRole,
                 RequiredRoleToModify:$modifyRole,
                 QueriesFolder:$queries,
                 HighlightsFolder:$highlights }')

            # ---------- Upsert JSON keys ----------
            az appconfig kv set --connection-string "$CS" \
              --key "Feature:AutoUpdate" \
              "${labelFlag[@]}" \
              --value "$AUTO_JSON" \
              --content-type "application/json" \
              --yes

            az appconfig kv set --connection-string "$CS" \
              --key "Feature:DataExplorer" \
              "${labelFlag[@]}" \
              --value "$DEX_JSON" \
              --content-type "application/json" \
              --yes
